"""
Praxis → TypeScript code generator (Sprint 14 — Pillar 5).

Compiles a Praxis Program AST to a standalone TypeScript module that:
  - Imports a minimal Praxis runtime (embedded or via @praxis-lang/runtime)
  - Executes each step as an async dispatch call
  - Converts PAR blocks to Promise.all([...])
  - Converts IF/LOOP/BREAK/SET/CALL/WAIT to equivalent TS constructs
  - Returns a structured array of StepResult objects

Usage:
    from praxis import parse
    from praxis.codegen.typescript import TypeScriptGenerator, RUNTIME_STUB

    program = parse("ING.sales -> CLN.normalize -> PAR(SUMM.text, EVAL.quality)")
    gen = TypeScriptGenerator()
    ts_code = gen.generate(program)
    print(ts_code)

The generated module exports:
  - async function run(ctx?: PraxisContext): Promise<StepResult[]>
  - type PraxisContext = Record<string, unknown>
  - type StepResult = { verb, target, status, output, duration_ms }

RUNTIME_STUB is the minimal TS runtime that must be present alongside the
generated file (or bundled). It provides the PraxisRuntime class with dispatch().
"""
from __future__ import annotations

import json
from textwrap import indent
from typing import Any

from praxis.ast_types import (
    Program, Chain, VerbAction, ParBlock, IfStmt, LoopStmt,
    Block, GoalDecl, PlanDecl, Skip, Break, Wait,
    VarRef, NamedCond, Comparison, OrExpr, AndExpr, NotExpr,
)


# ─────────────────────────────────────────────────────────────────────────────
# Minimal runtime that ships alongside generated code
# ─────────────────────────────────────────────────────────────────────────────

RUNTIME_STUB = '''\
/**
 * Praxis Runtime Stub — generated by praxis compile --target typescript
 * Replace dispatch() bodies with real implementations for your platform.
 */

export type PraxisContext = {
  variables: Record<string, unknown>;
  lastOutput: unknown;
};

export type StepResult = {
  verb: string;
  target: string[];
  params: Record<string, unknown>;
  status: "ok" | "error" | "skipped";
  output: unknown;
  duration_ms: number;
};

export class PraxisRuntime {
  private handlers: Record<string, (target: string[], params: Record<string, unknown>, ctx: PraxisContext) => Promise<unknown>>;

  constructor(handlers?: Record<string, (target: string[], params: Record<string, unknown>, ctx: PraxisContext) => Promise<unknown>>) {
    this.handlers = handlers ?? {};
  }

  async dispatch(verb: string, target: string[], params: Record<string, unknown>, ctx: PraxisContext): Promise<StepResult> {
    const start = Date.now();
    try {
      const handler = this.handlers[verb];
      const output = handler ? await handler(target, params, ctx) : null;
      const duration_ms = Date.now() - start;
      ctx.lastOutput = output;
      return { verb, target, params, status: "ok", output, duration_ms };
    } catch (err) {
      const duration_ms = Date.now() - start;
      return { verb, target, params, status: "error", output: null, duration_ms };
    }
  }
}

export function createRuntime(handlers?: Record<string, (target: string[], params: Record<string, unknown>, ctx: PraxisContext) => Promise<unknown>>): PraxisRuntime {
  return new PraxisRuntime(handlers);
}
'''


# ─────────────────────────────────────────────────────────────────────────────
# Generator
# ─────────────────────────────────────────────────────────────────────────────

class TypeScriptGenerator:
    """
    Compile a Praxis Program AST to a TypeScript module string.

    Parameters
    ----------
    runtime_import : str
        Import path for the runtime. Defaults to "./praxis-runtime" (local file).
        Use "@praxis-lang/runtime" if publishing to npm.
    embed_runtime : bool
        If True, prepend RUNTIME_STUB to the output instead of emitting an import.
    """

    def __init__(
        self,
        runtime_import: str = "./praxis-runtime",
        embed_runtime: bool = False,
    ) -> None:
        self.runtime_import = runtime_import
        self.embed_runtime = embed_runtime
        self._step_counter = 0
        self._indent_level = 0

    def generate(self, program: Program, source_text: str = "") -> str:
        """Return a complete TypeScript module for the given program."""
        self._step_counter = 0

        lines: list[str] = []

        # File header
        if source_text:
            lines.append(f"// Compiled from: {source_text.strip()[:80]}")
        lines.append("// Generated by praxis compile --target typescript")
        lines.append("")

        if self.embed_runtime:
            lines.append(RUNTIME_STUB)
        else:
            lines.append(f'import {{ PraxisRuntime, PraxisContext, StepResult, createRuntime }} from "{self.runtime_import}";')
            lines.append("")

        lines.append("const runtime = createRuntime();")
        lines.append("")
        lines.append("export async function run(initialCtx?: Partial<PraxisContext>): Promise<StepResult[]> {")
        lines.append("  const ctx: PraxisContext = { variables: {}, lastOutput: null, ...initialCtx };")
        lines.append("  const results: StepResult[] = [];")
        lines.append("")

        # Collect PLAN declarations first
        plan_decls = [s for s in program.statements if isinstance(s, PlanDecl)]
        exec_stmts = [s for s in program.statements if not isinstance(s, (GoalDecl, PlanDecl))]

        # Emit plan sub-functions
        for plan in plan_decls:
            plan_body = self._gen_plan(plan)
            lines.append(plan_body)

        # Emit main body
        for stmt in exec_stmts:
            body = self._gen_node(stmt, indent_n=1)
            lines.append(body)

        lines.append("  return results;")
        lines.append("}")
        lines.append("")

        return "\n".join(lines)

    # ── Node dispatch ──────────────────────────────────────────────────────────

    def _gen_node(self, node: Any, indent_n: int = 1) -> str:
        pad = "  " * indent_n
        if isinstance(node, Chain):
            return self._gen_chain(node, indent_n)
        if isinstance(node, VerbAction):
            return self._gen_verb(node, indent_n)
        if isinstance(node, ParBlock):
            return self._gen_par(node, indent_n)
        if isinstance(node, IfStmt):
            return self._gen_if(node, indent_n)
        if isinstance(node, LoopStmt):
            return self._gen_loop(node, indent_n)
        if isinstance(node, Block):
            return self._gen_block(node, indent_n)
        if isinstance(node, Skip):
            return f"{pad}// SKIP"
        if isinstance(node, Break):
            return f"{pad}break;"
        if isinstance(node, Wait):
            secs = float(node.params.get("seconds", 0)) if hasattr(node, "params") else 0
            ms = int(secs * 1000)
            return f"{pad}await new Promise(r => setTimeout(r, {ms}));"
        return f"{pad}// unhandled node: {type(node).__name__}"

    # ── Chain ──────────────────────────────────────────────────────────────────

    def _gen_chain(self, chain: Chain, indent_n: int) -> str:
        parts = [self._gen_node(step, indent_n) for step in chain.steps]
        return "\n".join(p for p in parts if p)

    # ── Verb ───────────────────────────────────────────────────────────────────

    def _gen_verb(self, action: VerbAction, indent_n: int) -> str:
        pad = "  " * indent_n
        step_var = f"step{self._step_counter}"
        self._step_counter += 1

        verb = json.dumps(action.verb)
        target = json.dumps(action.target)
        params = json.dumps(self._serialize_params(action.params))

        # Special: SET captures lastOutput into ctx.variables
        if action.verb == "SET":
            var_name = action.target[0] if action.target else "_"
            return (
                f"{pad}ctx.variables[{json.dumps(var_name)}] = ctx.lastOutput;\n"
                f"{pad}const {step_var}: StepResult = {{ verb: \"SET\", target: {target}, "
                f"params: {{}}, status: \"ok\", output: ctx.lastOutput, duration_ms: 0 }};\n"
                f"{pad}results.push({step_var});"
            )

        # Special: CALL invokes a plan sub-function
        if action.verb == "CALL":
            plan_name = action.target[0] if action.target else ""
            fn_name = f"plan_{_safe_id(plan_name)}"
            return (
                f"{pad}const {step_var}_results = await {fn_name}(ctx);\n"
                f"{pad}results.push(...{step_var}_results);\n"
                f"{pad}if ({step_var}_results.length > 0) {{ ctx.lastOutput = {step_var}_results[{step_var}_results.length - 1].output; }}"
            )

        return (
            f"{pad}const {step_var} = await runtime.dispatch({verb}, {target}, {params}, ctx);\n"
            f"{pad}results.push({step_var});"
        )

    # ── PAR ────────────────────────────────────────────────────────────────────

    def _gen_par(self, par: ParBlock, indent_n: int) -> str:
        pad = "  " * indent_n
        branch_vars = []
        setup_lines = []

        for branch in par.branches:
            if isinstance(branch, VerbAction):
                v = json.dumps(branch.verb)
                t = json.dumps(branch.target)
                p = json.dumps(self._serialize_params(branch.params))
                expr = f"runtime.dispatch({v}, {t}, {p}, ctx)"
                branch_vars.append(expr)

        if not branch_vars:
            return f"{pad}// PAR block — no branches"

        par_var = f"par{self._step_counter}"
        self._step_counter += 1

        branches_str = ",\n" + "  " * (indent_n + 1)
        branches_str = branches_str.join(branch_vars)
        lines = [
            f"{pad}const {par_var} = await Promise.all([",
            f"{'  ' * (indent_n + 1)}{branches_str}",
            f"{pad}]);",
            f"{pad}results.push(...{par_var});",
            f"{pad}if ({par_var}.length > 0) {{ ctx.lastOutput = {par_var}[{par_var}.length - 1].output; }}",
        ]
        return "\n".join(lines)

    # ── IF ─────────────────────────────────────────────────────────────────────

    def _gen_if(self, stmt: IfStmt, indent_n: int) -> str:
        pad = "  " * indent_n
        cond = self._gen_expr(stmt.condition)
        then_code = self._gen_node(stmt.then_body, indent_n + 1)
        parts = [f"{pad}if ({cond}) {{", then_code, f"{pad}}}"]
        if stmt.else_body is not None:
            else_code = self._gen_node(stmt.else_body, indent_n + 1)
            parts[-1] = f"{pad}}} else {{"
            parts.append(else_code)
            parts.append(f"{pad}}}")
        return "\n".join(parts)

    # ── LOOP ───────────────────────────────────────────────────────────────────

    def _gen_loop(self, stmt: LoopStmt, indent_n: int) -> str:
        pad = "  " * indent_n
        until_cond = self._gen_expr(stmt.until)
        body_code = self._gen_node(stmt.body, indent_n + 1)
        return "\n".join([
            f"{pad}while (!({until_cond})) {{",
            body_code,
            f"{pad}}}",
        ])

    # ── Block ──────────────────────────────────────────────────────────────────

    def _gen_block(self, block: Block, indent_n: int) -> str:
        return "\n".join(self._gen_node(s, indent_n) for s in block.statements)

    # ── PLAN sub-function ──────────────────────────────────────────────────────

    def _gen_plan(self, plan: PlanDecl) -> str:
        fn_name = f"plan_{_safe_id(plan.name)}"
        body = self._gen_node(plan.body, indent_n=2)
        return "\n".join([
            f"async function {fn_name}(ctx: PraxisContext): Promise<StepResult[]> {{",
            "  const results: StepResult[] = [];",
            body,
            "  return results;",
            "}",
            "",
        ])

    # ── Expression ─────────────────────────────────────────────────────────────

    def _gen_expr(self, expr: Any) -> str:
        if isinstance(expr, NamedCond):
            return f"Boolean(ctx.variables[{json.dumps(expr.name)}])"
        if isinstance(expr, VarRef):
            return f"Boolean(ctx.variables[{json.dumps(expr.name)}])"
        if isinstance(expr, Comparison):
            left = self._gen_operand(expr.left)
            right = self._gen_operand(expr.right)
            op_map = {">": ">", "<": "<", ">=": ">=", "<=": "<=", "==": "===", "!=": "!=="}
            op = op_map.get(expr.op, expr.op)
            return f"({left} {op} {right})"
        if isinstance(expr, OrExpr):
            return "(" + " || ".join(self._gen_expr(e) for e in expr.operands) + ")"
        if isinstance(expr, AndExpr):
            return "(" + " && ".join(self._gen_expr(e) for e in expr.operands) + ")"
        if isinstance(expr, NotExpr):
            return f"!({self._gen_expr(expr.operand)})"
        return "false"

    def _gen_operand(self, operand: Any) -> str:
        if isinstance(operand, VarRef):
            return f"ctx.variables[{json.dumps(operand.name)}]"
        return json.dumps(operand)

    # ── Param serialization ────────────────────────────────────────────────────

    def _serialize_params(self, params: dict) -> dict:
        result = {}
        for k, v in params.items():
            if isinstance(v, VarRef):
                # Runtime: resolve from ctx.variables at execution time
                # We encode as a special marker; real runtime should resolve
                result[k] = f"$var:{v.name}"
            elif isinstance(v, list):
                result[k] = [
                    f"$var:{i.name}" if isinstance(i, VarRef) else i
                    for i in v
                ]
            else:
                result[k] = v
        return result


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def _safe_id(name: str) -> str:
    """Convert a Praxis identifier to a safe TypeScript identifier."""
    return "".join(c if c.isalnum() or c == "_" else "_" for c in name)
