"""
Praxis → WebAssembly Text Format (WAT) code generator (Sprint 17 — Pillar 2-PartB).

Compiles a Praxis Program AST to a WAT module that can be assembled with
`wat2wasm` and loaded in any WASM runtime (browsers, Deno, Node.js, WasmEdge).

The generated module:
  - Exports a `run` function that returns a step count (i32)
  - Imports a `dispatch` host function for each verb execution
    (the host provides the actual handler implementations)
  - Encodes each VerbAction as a call to `dispatch` with:
      verb_id   (i32 index into the module's verb table)
      target_id (i32 index into the target table)
      step_idx  (i32 sequential step number)
  - PAR blocks emit sequential dispatches (WASM is single-threaded by default;
    true parallelism requires WASM threads + shared memory which is runtime-specific)
  - IF/LOOP compile to WASM if/block/br_if constructs
  - Variables stored in WASM linear memory as i32 indices into a string table

Design decisions:
  - Keeps the WAT output human-readable and small
  - String data (verb names, targets) stored as imported memory segments
  - The host dispatch() function handles the actual I/O; WASM is pure control flow
  - No WASM GC proposal required — all data is i32 indices
  - Compatible with wat2wasm 1.0+ and wasm-pack

Usage:
    from praxis import parse
    from praxis.codegen.wasm import WasmGenerator

    program = parse("LOG.a -> ANNOTATE.b -> OUT.c")
    gen = WasmGenerator()
    wat = gen.generate(program)
    # Write to file: Path("program.wat").write_text(wat)
    # Assemble: wat2wasm program.wat -o program.wasm
"""
from __future__ import annotations

from typing import Any

from praxis.ast_types import (
    Program, Chain, VerbAction, ParBlock, IfStmt, LoopStmt,
    Block, GoalDecl, PlanDecl, Skip, Break, Wait,
    VarRef, NamedCond, Comparison, OrExpr, AndExpr, NotExpr,
)


# ─────────────────────────────────────────────────────────────────────────────
# Generator
# ─────────────────────────────────────────────────────────────────────────────

class WasmGenerator:
    """
    Compile a Praxis Program AST to WebAssembly Text Format (WAT).

    The generated module:
      imports:
        env.dispatch(verb_id: i32, target_id: i32, step_idx: i32) -> i32
        env.set_var(var_id: i32, value: i32) -> void
        env.get_var(var_id: i32) -> i32
        env.sleep_ms(ms: i32) -> void

      exports:
        run() -> i32    (returns total step count)

      data section:
        verb names and target strings interned as null-terminated segments
    """

    def __init__(self) -> None:
        self._step_count = 0
        self._strings: list[str] = []   # interned string table
        self._string_index: dict[str, int] = {}
        self._loop_depth = 0

    def generate(self, program: Program, source_text: str = "") -> str:
        """Return a complete WAT module for the given program."""
        self._step_count = 0
        self._strings = []
        self._string_index = {}
        self._loop_depth = 0

        # Pre-pass: collect all strings
        exec_stmts = [s for s in program.statements
                      if not isinstance(s, (GoalDecl, PlanDecl))]
        plan_decls = [s for s in program.statements if isinstance(s, PlanDecl)]

        for stmt in exec_stmts + plan_decls:
            self._collect_strings(stmt)

        # Build body
        body_lines = []
        for stmt in exec_stmts:
            body_lines.extend(self._emit_node(stmt, indent=2))

        plan_functions = []
        for plan in plan_decls:
            plan_functions.extend(self._emit_plan(plan))

        # Build data section
        data_section = self._build_data_section()

        lines = [
            f";; Praxis WAT — generated by praxis compile --target wasm",
        ]
        if source_text:
            lines.append(f";; Source: {source_text.strip()[:60]}")
        lines.append("(module")
        lines.append("")
        lines.append("  ;; Host imports")
        lines.append('  (import "env" "dispatch"')
        lines.append('    (func $dispatch (param i32 i32 i32) (result i32)))')
        lines.append('  (import "env" "set_var"')
        lines.append('    (func $set_var (param i32 i32)))')
        lines.append('  (import "env" "get_var"')
        lines.append('    (func $get_var (param i32) (result i32)))')
        lines.append('  (import "env" "sleep_ms"')
        lines.append('    (func $sleep_ms (param i32)))')
        lines.append("")
        lines.append("  ;; Step counter global")
        lines.append("  (global $step_count (mut i32) (i32.const 0))")
        lines.append("")

        if plan_functions:
            lines.append("  ;; Plan sub-functions")
            for fn_line in plan_functions:
                lines.append(f"  {fn_line}")
            lines.append("")

        lines.append("  ;; Main run function")
        lines.append("  (func $run (export \"run\") (result i32)")
        for body_line in body_lines:
            lines.append(body_line)
        lines.append("    global.get $step_count")
        lines.append("  )")
        lines.append("")

        if data_section:
            lines.append("  ;; String data section")
            lines.append("  (memory (export \"memory\") 1)")
            for ds_line in data_section:
                lines.append(f"  {ds_line}")

        lines.append(")")
        lines.append("")

        return "\n".join(lines)

    # ── Node dispatch ──────────────────────────────────────────────────────────

    def _emit_node(self, node: Any, indent: int) -> list[str]:
        pad = "  " * indent
        if isinstance(node, Chain):
            return self._emit_chain(node, indent)
        if isinstance(node, VerbAction):
            return self._emit_verb(node, indent)
        if isinstance(node, ParBlock):
            return self._emit_par(node, indent)
        if isinstance(node, IfStmt):
            return self._emit_if(node, indent)
        if isinstance(node, LoopStmt):
            return self._emit_loop(node, indent)
        if isinstance(node, Block):
            lines = []
            for s in node.statements:
                lines.extend(self._emit_node(s, indent))
            return lines
        if isinstance(node, Skip):
            return [f"{pad};; SKIP (no-op)"]
        if isinstance(node, Break):
            return [f"{pad}br $loop_{self._loop_depth}"]
        if isinstance(node, Wait):
            secs = float(node.params.get("seconds", 0)) if hasattr(node, "params") else 0
            ms = int(secs * 1000)
            return [f"{pad}i32.const {ms}", f"{pad}call $sleep_ms"]
        return [f"{pad};; unhandled: {type(node).__name__}"]

    # ── Chain ──────────────────────────────────────────────────────────────────

    def _emit_chain(self, chain: Chain, indent: int) -> list[str]:
        lines = []
        for step in chain.steps:
            lines.extend(self._emit_node(step, indent))
        return lines

    # ── Verb ───────────────────────────────────────────────────────────────────

    def _emit_verb(self, action: VerbAction, indent: int) -> list[str]:
        pad = "  " * indent
        verb_id = self._intern(action.verb)
        target_str = ".".join(action.target) if action.target else ""
        target_id = self._intern(target_str)
        step_idx = self._step_count
        self._step_count += 1

        lines = [
            f"{pad};; {action.verb}.{target_str}",
            f"{pad}global.get $step_count",
            f"{pad}i32.const 1",
            f"{pad}i32.add",
            f"{pad}global.set $step_count",
            f"{pad}i32.const {verb_id}    ;; verb: {action.verb}",
            f"{pad}i32.const {target_id}  ;; target: {target_str or '(none)'}",
            f"{pad}i32.const {step_idx}   ;; step index",
            f"{pad}call $dispatch",
            f"{pad}drop  ;; discard return value (step status)",
        ]

        # SET: call $set_var with var index and current value (last_output ~ step_idx)
        if action.verb == "SET" and action.target:
            var_id = self._intern(action.target[0])
            lines.extend([
                f"{pad};; SET.{action.target[0]} — store last step result",
                f"{pad}i32.const {var_id}",
                f"{pad}i32.const {step_idx}  ;; last step index as value proxy",
                f"{pad}call $set_var",
            ])

        return lines

    # ── PAR ────────────────────────────────────────────────────────────────────

    def _emit_par(self, par: ParBlock, indent: int) -> list[str]:
        """
        PAR in WAT is sequential (WASM threads require separate proposal).
        Emits each branch in order with a comment indicating parallelism intent.
        """
        pad = "  " * indent
        lines = [f"{pad};; PAR block — sequential in single-threaded WASM"]
        for branch in par.branches:
            lines.extend(self._emit_node(branch, indent))
        return lines

    # ── IF ─────────────────────────────────────────────────────────────────────

    def _emit_if(self, stmt: IfStmt, indent: int) -> list[str]:
        pad = "  " * indent
        lines = []

        # Emit condition
        cond_lines = self._emit_cond(stmt.condition, indent)
        lines.extend(cond_lines)

        lines.append(f"{pad}(if")
        lines.append(f"{pad}  (then")
        for ln in self._emit_node(stmt.then_body, indent + 2):
            lines.append(ln)
        lines.append(f"{pad}  )")

        if stmt.else_body is not None:
            lines.append(f"{pad}  (else")
            for ln in self._emit_node(stmt.else_body, indent + 2):
                lines.append(ln)
            lines.append(f"{pad}  )")

        lines.append(f"{pad})")
        return lines

    # ── LOOP ───────────────────────────────────────────────────────────────────

    def _emit_loop(self, stmt: LoopStmt, indent: int) -> list[str]:
        pad = "  " * indent
        self._loop_depth += 1
        depth = self._loop_depth

        lines = [
            f"{pad}(block $loop_{depth}",
            f"{pad}  (loop $loop_inner_{depth}",
        ]
        # Check UNTIL condition — break out of outer block if true
        cond_lines = self._emit_cond(stmt.until, indent + 2)
        lines.extend(cond_lines)
        lines.append(f"{pad}    (if (then br $loop_{depth}))")
        # Body
        for ln in self._emit_node(stmt.body, indent + 2):
            lines.append(ln)
        # Back edge
        lines.append(f"{pad}    br $loop_inner_{depth}")
        lines.append(f"{pad}  )")
        lines.append(f"{pad})")

        self._loop_depth -= 1
        return lines

    # ── Condition ──────────────────────────────────────────────────────────────

    def _emit_cond(self, expr: Any, indent: int) -> list[str]:
        pad = "  " * indent
        if isinstance(expr, NamedCond):
            var_id = self._intern(expr.name)
            return [f"{pad}i32.const {var_id}", f"{pad}call $get_var"]
        if isinstance(expr, VarRef):
            var_id = self._intern(expr.name)
            return [f"{pad}i32.const {var_id}", f"{pad}call $get_var"]
        if isinstance(expr, Comparison):
            left_lines = self._emit_operand(expr.left, indent)
            right_lines = self._emit_operand(expr.right, indent)
            op_map = {
                ">":  "i32.gt_s", "<":  "i32.lt_s",
                ">=": "i32.ge_s", "<=": "i32.le_s",
                "==": "i32.eq",   "!=": "i32.ne",
            }
            op = op_map.get(expr.op, "i32.eq")
            return left_lines + right_lines + [f"{pad}{op}"]
        if isinstance(expr, NotExpr):
            inner = self._emit_cond(expr.operand, indent)
            return inner + [f"{pad}i32.eqz"]
        if isinstance(expr, AndExpr):
            lines = []
            for e in expr.operands:
                lines.extend(self._emit_cond(e, indent))
            for _ in range(len(expr.operands) - 1):
                lines.append(f"{pad}i32.and")
            return lines
        if isinstance(expr, OrExpr):
            lines = []
            for e in expr.operands:
                lines.extend(self._emit_cond(e, indent))
            for _ in range(len(expr.operands) - 1):
                lines.append(f"{pad}i32.or")
            return lines
        return [f"{pad}i32.const 0  ;; unknown condition"]

    def _emit_operand(self, operand: Any, indent: int) -> list[str]:
        pad = "  " * indent
        if isinstance(operand, VarRef):
            var_id = self._intern(operand.name)
            return [f"{pad}i32.const {var_id}", f"{pad}call $get_var"]
        if isinstance(operand, (int, float)):
            return [f"{pad}i32.const {int(operand)}"]
        if isinstance(operand, str):
            str_id = self._intern(operand)
            return [f"{pad}i32.const {str_id}"]
        return [f"{pad}i32.const 0"]

    # ── PLAN sub-function ──────────────────────────────────────────────────────

    def _emit_plan(self, plan: PlanDecl) -> list[str]:
        from praxis.codegen.typescript import _safe_id
        fn_name = f"plan_{_safe_id(plan.name)}"
        lines = [f"(func ${fn_name} (export \"{fn_name}\")"]
        for ln in self._emit_node(plan.body, indent=1):
            lines.append(ln)
        lines.append(")")
        return lines

    # ── String interning ───────────────────────────────────────────────────────

    def _intern(self, s: str) -> int:
        if s not in self._string_index:
            self._string_index[s] = len(self._strings)
            self._strings.append(s)
        return self._string_index[s]

    def _collect_strings(self, node: Any) -> None:
        if isinstance(node, VerbAction):
            self._intern(node.verb)
            self._intern(".".join(node.target) if node.target else "")
            for v in node.params.values():
                if isinstance(v, str):
                    self._intern(v)
        elif isinstance(node, Chain):
            for s in node.steps:
                self._collect_strings(s)
        elif isinstance(node, Block):
            for s in node.statements:
                self._collect_strings(s)
        elif isinstance(node, ParBlock):
            for b in node.branches:
                self._collect_strings(b)
        elif isinstance(node, IfStmt):
            self._collect_strings(node.then_body)
            if node.else_body:
                self._collect_strings(node.else_body)
        elif isinstance(node, LoopStmt):
            self._collect_strings(node.body)
        elif isinstance(node, PlanDecl):
            self._collect_strings(node.body)

    # ── Data section ───────────────────────────────────────────────────────────

    def _build_data_section(self) -> list[str]:
        """
        Build WAT data segment entries for the interned string table.
        Each string is null-terminated and laid out sequentially from offset 0.
        """
        if not self._strings:
            return []

        lines = [";; Interned string table (null-terminated)"]
        offset = 0
        for idx, s in enumerate(self._strings):
            escaped = s.replace("\\", "\\\\").replace('"', '\\"')
            byte_count = len(s.encode()) + 1  # +1 for null terminator
            lines.append(f'(data (i32.const {offset}) "{escaped}\\00")  ;; [{idx}] {s!r}')
            offset += byte_count
        return lines
