"""
Sprint 14 tests — TypeScript runtime adapter + praxis compile.
"""
from __future__ import annotations

import tempfile
from pathlib import Path

import pytest
from click.testing import CliRunner

from praxis import parse
from praxis.codegen.typescript import TypeScriptGenerator, RUNTIME_STUB, _safe_id
from praxis.ast_types import (
    Program, Chain, VerbAction, ParBlock, IfStmt, Block, PlanDecl,
    NamedCond, Comparison, VarRef,
)
from praxis.cli import main


# ─── helpers ──────────────────────────────────────────────────────────────────

def _gen(text: str, **kwargs) -> str:
    gen = TypeScriptGenerator(**kwargs)
    return gen.generate(parse(text))


def _prog(*steps) -> Program:
    return Program(statements=[Chain(steps=list(steps))])


# ══════════════════════════════════════════════════════════════════════════════
# RUNTIME_STUB
# ══════════════════════════════════════════════════════════════════════════════

class TestRuntimeStub:
    def test_stub_is_string(self):
        assert isinstance(RUNTIME_STUB, str)

    def test_stub_contains_praxis_runtime_class(self):
        assert "PraxisRuntime" in RUNTIME_STUB

    def test_stub_contains_dispatch(self):
        assert "dispatch" in RUNTIME_STUB

    def test_stub_contains_step_result_type(self):
        assert "StepResult" in RUNTIME_STUB

    def test_stub_contains_create_runtime(self):
        assert "createRuntime" in RUNTIME_STUB

    def test_stub_contains_context_type(self):
        assert "PraxisContext" in RUNTIME_STUB


# ══════════════════════════════════════════════════════════════════════════════
# TypeScriptGenerator basics
# ══════════════════════════════════════════════════════════════════════════════

class TestGeneratorBasics:
    def test_returns_string(self):
        assert isinstance(_gen("LOG.test"), str)

    def test_contains_run_function(self):
        assert "async function run" in _gen("LOG.test")

    def test_contains_import_by_default(self):
        ts = _gen("LOG.test")
        assert "import" in ts
        assert "praxis-runtime" in ts

    def test_embed_runtime_omits_import(self):
        ts = _gen("LOG.test", embed_runtime=True)
        assert 'import {' not in ts

    def test_embed_runtime_includes_stub(self):
        ts = _gen("LOG.test", embed_runtime=True)
        assert "PraxisRuntime" in ts

    def test_custom_runtime_import(self):
        ts = _gen("LOG.test", runtime_import="@praxis-lang/runtime")
        assert "@praxis-lang/runtime" in ts

    def test_contains_results_array(self):
        assert "results: StepResult[]" in _gen("LOG.test")

    def test_returns_results(self):
        assert "return results" in _gen("LOG.test")

    def test_generated_comment_header(self):
        ts = _gen("LOG.test")
        assert "Generated by praxis compile" in ts


# ══════════════════════════════════════════════════════════════════════════════
# Verb dispatch
# ══════════════════════════════════════════════════════════════════════════════

class TestVerbDispatch:
    def test_verb_name_in_output(self):
        assert '"LOG"' in _gen("LOG.test")

    def test_target_in_output(self):
        assert '"test"' in _gen("LOG.test")

    def test_runtime_dispatch_called(self):
        assert "runtime.dispatch" in _gen("LOG.test")

    def test_await_present(self):
        assert "await" in _gen("LOG.test")

    def test_results_push_present(self):
        assert "results.push" in _gen("LOG.test")

    def test_multiple_steps_generate_multiple_dispatches(self):
        ts = _gen("LOG.a -> ANNOTATE.b -> OUT.c")
        assert ts.count("runtime.dispatch") == 3

    def test_set_verb_assigns_to_ctx_variables(self):
        steps = [
            VerbAction(verb="LOG", target=["x"], params={}),
            VerbAction(verb="SET", target=["myvar"], params={}),
        ]
        ts = TypeScriptGenerator().generate(_prog(*steps))
        assert "ctx.variables" in ts
        assert '"myvar"' in ts

    def test_params_serialized(self):
        ts = _gen('LOG.test(level=info)')
        assert "level" in ts or "info" in ts


# ══════════════════════════════════════════════════════════════════════════════
# PAR block
# ══════════════════════════════════════════════════════════════════════════════

class TestParBlock:
    def test_par_uses_promise_all(self):
        par = ParBlock(branches=[
            VerbAction(verb="LOG", target=["a"], params={}),
            VerbAction(verb="ANNOTATE", target=["b"], params={}),
        ])
        ts = TypeScriptGenerator().generate(_prog(par))
        assert "Promise.all" in ts

    def test_par_contains_both_verbs(self):
        par = ParBlock(branches=[
            VerbAction(verb="LOG", target=["a"], params={}),
            VerbAction(verb="ANNOTATE", target=["b"], params={}),
        ])
        ts = TypeScriptGenerator().generate(_prog(par))
        assert '"LOG"' in ts
        assert '"ANNOTATE"' in ts

    def test_par_results_pushed(self):
        par = ParBlock(branches=[
            VerbAction(verb="LOG", target=["a"], params={}),
            VerbAction(verb="OUT", target=["b"], params={}),
        ])
        ts = TypeScriptGenerator().generate(_prog(par))
        assert "results.push" in ts


# ══════════════════════════════════════════════════════════════════════════════
# IF / condition
# ══════════════════════════════════════════════════════════════════════════════

class TestIfStatement:
    def test_if_generates_ts_if(self):
        cond = NamedCond(name="my_flag")
        then = VerbAction(verb="LOG", target=["x"], params={})
        stmt = IfStmt(condition=cond, then_body=then, else_body=None)
        ts = TypeScriptGenerator().generate(Program(statements=[stmt]))
        assert "if (" in ts

    def test_else_body_generated(self):
        cond = NamedCond(name="flag")
        then = VerbAction(verb="LOG", target=["x"], params={})
        else_ = VerbAction(verb="ANNOTATE", target=["y"], params={})
        stmt = IfStmt(condition=cond, then_body=then, else_body=else_)
        ts = TypeScriptGenerator().generate(Program(statements=[stmt]))
        assert "} else {" in ts

    def test_comparison_operator_mapped(self):
        cond = Comparison(left=VarRef(name="x"), op="==", right=5)
        then = VerbAction(verb="LOG", target=["y"], params={})
        stmt = IfStmt(condition=cond, then_body=then, else_body=None)
        ts = TypeScriptGenerator().generate(Program(statements=[stmt]))
        assert "===" in ts  # Praxis == → TypeScript ===


# ══════════════════════════════════════════════════════════════════════════════
# _safe_id helper
# ══════════════════════════════════════════════════════════════════════════════

class TestSafeId:
    def test_plain_name_unchanged(self):
        assert _safe_id("my_plan") == "my_plan"

    def test_spaces_replaced_with_underscore(self):
        assert " " not in _safe_id("my plan")

    def test_hyphens_replaced(self):
        assert "-" not in _safe_id("my-plan")

    def test_alphanumeric_preserved(self):
        assert _safe_id("plan123") == "plan123"


# ══════════════════════════════════════════════════════════════════════════════
# CLI: praxis compile
# ══════════════════════════════════════════════════════════════════════════════

class TestCompileCLI:
    def test_compile_outputs_typescript(self):
        runner = CliRunner()
        result = runner.invoke(main, ["compile", "LOG.test"])
        assert result.exit_code == 0
        assert "async function run" in result.output

    def test_compile_target_typescript_explicit(self):
        runner = CliRunner()
        result = runner.invoke(main, ["compile", "--target", "typescript", "LOG.test"])
        assert result.exit_code == 0

    def test_compile_to_file(self):
        runner = CliRunner()
        with tempfile.TemporaryDirectory() as tmpdir:
            outfile = str(Path(tmpdir) / "output.ts")
            result = runner.invoke(main, ["compile", "LOG.test", "--out", outfile])
            assert result.exit_code == 0
            assert Path(outfile).exists()
            assert "async function run" in Path(outfile).read_text()

    def test_compile_to_file_writes_runtime_stub(self):
        runner = CliRunner()
        with tempfile.TemporaryDirectory() as tmpdir:
            outfile = str(Path(tmpdir) / "output.ts")
            result = runner.invoke(main, ["compile", "LOG.test", "--out", outfile])
            assert result.exit_code == 0
            runtime_file = Path(tmpdir) / "praxis-runtime.ts"
            assert runtime_file.exists()

    def test_compile_embed_runtime(self):
        runner = CliRunner()
        result = runner.invoke(main, ["compile", "--embed-runtime", "LOG.test"])
        assert result.exit_code == 0
        assert "PraxisRuntime" in result.output
        assert "import {" not in result.output

    def test_compile_invalid_program_exits_nonzero(self):
        runner = CliRunner()
        result = runner.invoke(main, ["compile", "NOT VALID !!!"])
        assert result.exit_code != 0

    def test_compile_from_file(self):
        runner = CliRunner()
        with tempfile.TemporaryDirectory() as tmpdir:
            px_file = str(Path(tmpdir) / "prog.px")
            Path(px_file).write_text("LOG.test -> ANNOTATE.x")
            result = runner.invoke(main, ["compile", "--file", px_file])
            assert result.exit_code == 0
            assert "LOG" in result.output
            assert "ANNOTATE" in result.output

    def test_compile_chain_generates_multiple_dispatches(self):
        runner = CliRunner()
        result = runner.invoke(main, ["compile", "LOG.a -> ANNOTATE.b -> OUT.c"])
        assert result.exit_code == 0
        assert result.output.count("runtime.dispatch") == 3
